# 把 Node.js 中的回调转换为 Promise
* [把 Node.js 中的回调转换为 Promise 原文链接](https://mp.weixin.qq.com/s/O3F4iOgN9YVyC0qYCWw_bg)
* [把 Node.js 中的回调转换为 Promise 原文链接](https://mp.weixin.qq.com/s/O3F4iOgN9YVyC0qYCWw_bg)
* [把 Node.js 中的回调转换为 Promise 原文链接](https://mp.weixin.qq.com/s/O3F4iOgN9YVyC0qYCWw_bg)


## 介绍
在 ES6 中引入了 Promise 作为这些问题的解决方案。
最后通过引入  async/await  关键字来提供更好的体验并提高了可读性。

即使有了新的方法，但是仍然有许多使用回调的原生模块和库。
在本文中，我们将讨论如何将 JavaScript 回调转换为 Promise。
ES6 的知识将会派上用场，因为我们将会使用 展开操作符之类的功能来简化要做的事情。

## 什么是回调
* [app.js](https://github.com/guopeng1129972/blog/blob/main/dome/003/app.js)
如果这段代码，应该在执行回调之前看到 0..9 被输出到控制台。
这是因为 JavaScript 的异步管理机制。
在读取文件完毕之后，输出文件内容的回调才被调用。

## 什么是 Promise
在 ECMAScript 2015（ES6）中引入了 Promise，用来改善在异步编程方面的体验。
顾名思义，JavaScript 对象最终将返回的“值”或“错误”应该是一个 Promise。

一个 Promise 有 3 个状态：
Pending（待处理）：用来指示异步操作尚未完成的初始状态。
Fulfilled（已完成）：表示异步操作已成功完成。
Rejected（拒绝）：表示异步操作失败。
```js
someAsynchronousFunction()
    .then(data => {
        // promise 被完成
        console.log(data);
    })
    .catch(err => {
        // promise 被拒绝
        console.error(err);
    });
```
Promise 在现代 JavaScript 中非常重要，
因为它们与 ECMAScript 2016 中引入的 async/await 关键字一起使用。
使用 async / await 就不需要再用回调或 then() 和 catch() 来编写异步代码。

如果要改写前面的例子，应该是这样：
```js
try {
    const data = await someAsynchronousFunction();
} catch(err) {
    // promise 被拒绝
    console.error(err);
}
```
这看起来很像“一般的”同步 JavaScript。
大多数流行的JavaScript库和新项目都把 Promises 与 async/await 关键字放在一起用。

但是，如果你要更新现有的库或遇到旧的代码，
则可能会对将基于回调的 API 迁移到基于 Promise 的 API 感兴趣，这样可以改善你的开发体验。

来看一下将回调转换为 Promise 的几种方法。
## 将回调转换为 Promise
### Node.js Promise
大多数在 Node.js 中接受回调的异步函数（例如 fs 模块）有标准的实现方式：
把回调作为最后一个参数传递。

例如这是在不指定文本编码的情况下用 fs.readFile() 读取文件的方法：
```js
fs.readFile('./sample.txt', (err, data) => {
    if (err) {
        console.error(err);
          return;
    }
    console.log(data);
});
```
注意：如果你指定 utf-8 作为编码，那么得到的输出是一个字符串。如果不指定得到的输出是 Buffer。

另外传给这个函数的回调应接受 Error，因为它是第一个参数。之后可以有任意数量的输出。

如果你需要转换为 Promise 的函数遵循这些规则，那么可以用 util.promisify ，这是一个原生 Node.js 模块，其中包含对 Promise 的回调。

首先导入ʻutil`模块：
```js
const util = require('util');
```
然后用 promisify 方法将其转换为 Promise：
```js
const fs = require('fs');
const readFile = util.promisify(fs.readFile);
```
现在，把新创建的函数用作 promise：
```js
readFile('./sample.txt', 'utf-8')
    .then(data => {
        console.log(data);
    })
    .catch(err => {
        console.log(err);
    });
```
另外也可以用下面这个示例中给出的 async/await 关键字：
```js
const fs = require('fs');
const util = require('util');

const readFile = util.promisify(fs.readFile);

(async () => {
    try {
        const content = await readFile('./sample.txt', 'utf-8');
        console.log(content);
    } catch (err) {
        console.error(err);
    }
})();
```
你只能在用 async 创建的函数中使用 await 关键字，这也是为什么要使用函数包装器的原因。
函数包装器也被称为立即调用的函数表达式。

如果你的回调不遵循这个特定标准也不用担心。
util.promisify() 函数可让你自定义转换是如何发生的。

### 创建你自己的 Promise
让我们讨论一下怎样把回调转为  util.promisify() 函数的 promise。
思路是创建一个新的包含回调函数的 Promise 对象。
如果回调函数返回错误，就拒绝带有该错误的Promise。
如果回调函数返回非错误输出，就解决并输出 Promise。
先把回调转换为一个接受固定参数的函数的 promise 开始：
```js
const fs = require('fs');

const readFile = (fileName, encoding) => {
    return new Promise((resolve, reject) => {
        fs.readFile(fileName, encoding, (err, data) => {
            if (err) {
                return reject(err);
            }

            resolve(data);
        });
    });
}

readFile('./sample.txt')
    .then(data => {
        console.log(data);
    })
    .catch(err => {
        console.log(err);
    });
```
新函数 readFile() 接受了用来读取 fs.readFile() 文件的两个参数。
然后创建一个新的 Promise 对象，该对象包装了该函数，
并接受回调，在本例中为 fs.readFile()。
要  reject  Promise 而不是返回错误。所以代码中没有立即把数据输出，
而是先 resolve 了Promise。
然后像以前一样使用基于 Promise 的 readFile() 函数。
接下来看看接受动态数量参数的函数：
```js
const getMaxCustom = (callback, ...args) => {
    //设置最大值为负无穷
    let max = -Infinity;

    for (let i of args) {
        if (i > max) {
            max = i;
        }
    }

    callback(max);
}

getMaxCustom((max) => { console.log('Max is ' + max) }, 10, 2, 23, 1, 111, 20);
```
第一个参数是 callback 参数，这使它在接受回调的函数中有点与众不同。
转换为 promise 的方式和上一个例子一样。创建一个新的 Promise 对象，
这个对象包装使用回调的函数。如果遇到错误，就 reject，当结果出现时将会 resolve。
我们的 promise 版本如下：
```js
const getMaxCustom = (callback, ...args) => {
    let max = -Infinity;
    for (let i of args) {
        if (i > max) {
            max = i;
        }
    }
    callback(max);
}

const getMaxPromise = (...args) => {
    return new Promise((resolve) => {
        getMaxCustom((max) => {
            resolve(max);
        }, ...args);
    });
}

getMaxPromise(10, 2, 23, 1, 111, 20)
    .then(max => console.log(max));

//文中的是不少了点啥
```